#!/usr/bin/env python
# (C) Copyright 2014- Dan Oblinger  <code@oblinger.us>

# Executes 'launcher' in its own console window

import os

folder = os.path.dirname(os.path.abspath(__file__))
os.system('open "%s/installer"' % folder)

