#!/usr/bin/env python

import os

INSTALLATION_FOLDER = '/Applications'
CTRL_SCRIPT         = 'Contents/MacOS/ctrl'

def installer_bootstrap():
    dest = INSTALLATION_FOLDER
    src_root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    dest_root = '%s/%s' % (dest, os.path.basename(src_root))

    print('\033[0;0H\033[2J\n\n  SPOTLIGHT-COMMANDER INSTALL')
    print("  (1) Copies application to %r\n      from %r" % (dest,src_root))
    print("  (2) Invokes 'SpotlightCommander --install'  to create initial commands")
    print("")
    print("  UNINSTALL INSTRUCTIONS")
    print("     -- Remove app from /Applications")
    print("     -- Remove the commands folder 'cmd' folder in the user's HOME folder.")
    ask=raw_input('\n\n  Perform installation [y/n]? ')
    if len(ask)<1 or ask.lower()[0]!='y':
        os.sys.exit(0)

    os.system('cp -r "%s" "%s"' % (src_root, dest))
    os.system('%s/%s --install' % (dest_root, CTRL_SCRIPT))

    raw_input('\nInstallation complete.  Press "return" to exit')

installer_bootstrap()





